//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IttezanPos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IttezanPos.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Hundred.
        /// </summary>
        internal static string _2Hundred {
            get {
                return ResourceManager.GetString("2Hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Hundred.
        /// </summary>
        internal static string _3Hundred {
            get {
                return ResourceManager.GetString("3Hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four Hundred.
        /// </summary>
        internal static string _4Hundred {
            get {
                return ResourceManager.GetString("4Hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five Hundred.
        /// </summary>
        internal static string _5Hundred {
            get {
                return ResourceManager.GetString("5Hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six Hundred.
        /// </summary>
        internal static string _6Hundred {
            get {
                return ResourceManager.GetString("6Hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Hundred.
        /// </summary>
        internal static string _7Hundred {
            get {
                return ResourceManager.GetString("7Hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eight Hundred.
        /// </summary>
        internal static string _8Hundred {
            get {
                return ResourceManager.GetString("8Hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine Hundred.
        /// </summary>
        internal static string _9Hundred {
            get {
                return ResourceManager.GetString("9Hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AAn {
            get {
                return ResourceManager.GetString("AAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddAddress.
        /// </summary>
        internal static string AddAddress {
            get {
                return ResourceManager.GetString("AddAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Client Limit.
        /// </summary>
        internal static string AddClientLimit {
            get {
                return ResourceManager.GetString("AddClientLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Client Name.
        /// </summary>
        internal static string AddClientName {
            get {
                return ResourceManager.GetString("AddClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Email Address.
        /// </summary>
        internal static string AddEmailAddress {
            get {
                return ResourceManager.GetString("AddEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product&apos;s Image.
        /// </summary>
        internal static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Category.
        /// </summary>
        internal static string AddingNewClassification {
            get {
                return ResourceManager.GetString("AddingNewClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Client.
        /// </summary>
        internal static string AddNewClient {
            get {
                return ResourceManager.GetString("AddNewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddNewProduct.
        /// </summary>
        internal static string AddNewProduct {
            get {
                return ResourceManager.GetString("AddNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Supplier.
        /// </summary>
        internal static string AddNewSupplier {
            get {
                return ResourceManager.GetString("AddNewSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Notes.
        /// </summary>
        internal static string AddNotes {
            get {
                return ResourceManager.GetString("AddNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Phone Number.
        /// </summary>
        internal static string AddPhoneNumber {
            get {
                return ResourceManager.GetString("AddPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sales and customer amounts to the fund.
        /// </summary>
        internal static string Addsalesandcustomeramountstothefund {
            get {
                return ResourceManager.GetString("Addsalesandcustomeramountstothefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Fund.
        /// </summary>
        internal static string AddToFund {
            get {
                return ResourceManager.GetString("AddToFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Alert .
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount owed.
        /// </summary>
        internal static string Amountowed {
            get {
                return ResourceManager.GetString("Amountowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount.
        /// </summary>
        internal static string Amountpaid {
            get {
                return ResourceManager.GetString("Amountpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount payable.
        /// </summary>
        internal static string Amountpayable {
            get {
                return ResourceManager.GetString("Amountpayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Office.
        /// </summary>
        internal static string BackOffice {
            get {
                return ResourceManager.GetString("BackOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarCode.
        /// </summary>
        internal static string BarCode {
            get {
                return ResourceManager.GetString("BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billion.
        /// </summary>
        internal static string Billion {
            get {
                return ResourceManager.GetString("Billion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billions.
        /// </summary>
        internal static string Billions {
            get {
                return ResourceManager.GetString("Billions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Settings.
        /// </summary>
        internal static string BusinessSettings {
            get {
                return ResourceManager.GetString("BusinessSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Quantity.
        /// </summary>
        internal static string ByQuantity {
            get {
                return ResourceManager.GetString("ByQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Unit.
        /// </summary>
        internal static string ByUnit {
            get {
                return ResourceManager.GetString("ByUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera 📷.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Permission is Needed.
        /// </summary>
        internal static string CameraPermissionsNeeded {
            get {
                return ResourceManager.GetString("CameraPermissionsNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Category.
        /// </summary>
        internal static string ChooseCategory {
            get {
                return ResourceManager.GetString("ChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Limit.
        /// </summary>
        internal static string ClientLimit {
            get {
                return ResourceManager.GetString("ClientLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        internal static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s Data.
        /// </summary>
        internal static string ClientsData {
            get {
                return ResourceManager.GetString("ClientsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connected , Please Check Your Connection.
        /// </summary>
        internal static string ConnectionNotAvailable {
            get {
                return ResourceManager.GetString("ConnectionNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s Opening Balances.
        /// </summary>
        internal static string Customeropeningbalances {
            get {
                return ResourceManager.GetString("Customeropeningbalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s Receivables - Reports.
        /// </summary>
        internal static string Customerreceivables {
            get {
                return ResourceManager.GetString("Customerreceivables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        internal static string Decrease {
            get {
                return ResourceManager.GetString("Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction from the Fund.
        /// </summary>
        internal static string DeductionfromtheFund {
            get {
                return ResourceManager.GetString("DeductionfromtheFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction of expenses from the Fund.
        /// </summary>
        internal static string DeductionofexpensesfromtheFund {
            get {
                return ResourceManager.GetString("DeductionofexpensesfromtheFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction of the amounts of purchases and suppliers from the Fund.
        /// </summary>
        internal static string DeductionoftheamountsofpurchasesandsuppliersfromtheFund {
            get {
                return ResourceManager.GetString("DeductionoftheamountsofpurchasesandsuppliersfromtheFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduct of Fund.
        /// </summary>
        internal static string DeductOfFund {
            get {
                return ResourceManager.GetString("DeductOfFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Client&apos;s Data Succesfully.
        /// </summary>
        internal static string DeletedClient {
            get {
                return ResourceManager.GetString("DeletedClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Supplier&apos;s Data Succesfully.
        /// </summary>
        internal static string DeletedSupplier {
            get {
                return ResourceManager.GetString("DeletedSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        internal static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edite.
        /// </summary>
        internal static string Edite {
            get {
                return ResourceManager.GetString("Edite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edite By Category.
        /// </summary>
        internal static string EditeByCategory {
            get {
                return ResourceManager.GetString("EditeByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edite Price.
        /// </summary>
        internal static string EditePrice {
            get {
                return ResourceManager.GetString("EditePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editting Prices.
        /// </summary>
        internal static string EdittingSalaries {
            get {
                return ResourceManager.GetString("EdittingSalaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eight.
        /// </summary>
        internal static string Eight {
            get {
                return ResourceManager.GetString("Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eighty.
        /// </summary>
        internal static string Eighty {
            get {
                return ResourceManager.GetString("Eighty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eleven.
        /// </summary>
        internal static string Eleven {
            get {
                return ResourceManager.GetString("Eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Cart.
        /// </summary>
        internal static string EmptyCart {
            get {
                return ResourceManager.GetString("EmptyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the amount.
        /// </summary>
        internal static string Entertheamount {
            get {
                return ResourceManager.GetString("Entertheamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, Check Your intenet Connection .
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        internal static string Expirationdate {
            get {
                return ResourceManager.GetString("Expirationdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        internal static string Extra {
            get {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Field is required.
        /// </summary>
        internal static string FieldReq {
            get {
                return ResourceManager.GetString("FieldReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifty.
        /// </summary>
        internal static string Fifty {
            get {
                return ResourceManager.GetString("Fifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five.
        /// </summary>
        internal static string Five {
            get {
                return ResourceManager.GetString("Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four.
        /// </summary>
        internal static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourty.
        /// </summary>
        internal static string Fourty {
            get {
                return ResourceManager.GetString("Fourty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery 🖼️.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hundred.
        /// </summary>
        internal static string Hundred {
            get {
                return ResourceManager.GetString("Hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impact on prices.
        /// </summary>
        internal static string Impactonprices {
            get {
                return ResourceManager.GetString("Impactonprices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Product Data From Excel.
        /// </summary>
        internal static string ImportProductData {
            get {
                return ResourceManager.GetString("ImportProductData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase.
        /// </summary>
        internal static string Increase {
            get {
                return ResourceManager.GetString("Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mail Format.
        /// </summary>
        internal static string InvalidMail {
            get {
                return ResourceManager.GetString("InvalidMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Log Out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Million.
        /// </summary>
        internal static string Million {
            get {
                return ResourceManager.GetString("Million", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millions.
        /// </summary>
        internal static string Millions {
            get {
                return ResourceManager.GetString("Millions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs Permission For Using Camera.
        /// </summary>
        internal static string NeedCamera {
            get {
                return ResourceManager.GetString("NeedCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine.
        /// </summary>
        internal static string Nine {
            get {
                return ResourceManager.GetString("Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninety.
        /// </summary>
        internal static string Ninety {
            get {
                return ResourceManager.GetString("Ninety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.Q.
        /// </summary>
        internal static string NQ {
            get {
                return ResourceManager.GetString("NQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        internal static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening balance for Clients.
        /// </summary>
        internal static string Openingbalanceforcustomers {
            get {
                return ResourceManager.GetString("Openingbalanceforcustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Type.
        /// </summary>
        internal static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage %.
        /// </summary>
        internal static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs Permission For Using Camera to choose Product Image.
        /// </summary>
        internal static string PermissionsDenied {
            get {
                return ResourceManager.GetString("PermissionsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        internal static string Printer {
            get {
                return ResourceManager.GetString("Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        internal static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase invoice date.
        /// </summary>
        internal static string PurchaseDate {
            get {
                return ResourceManager.GetString("PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing.
        /// </summary>
        internal static string Purchasing {
            get {
                return ResourceManager.GetString("Purchasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing price.
        /// </summary>
        internal static string Purchasingprice {
            get {
                return ResourceManager.GetString("Purchasingprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrillion.
        /// </summary>
        internal static string Quadrillion {
            get {
                return ResourceManager.GetString("Quadrillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrillions.
        /// </summary>
        internal static string Quadrillions {
            get {
                return ResourceManager.GetString("Quadrillions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipts.
        /// </summary>
        internal static string Recipts {
            get {
                return ResourceManager.GetString("Recipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representation On Pos.
        /// </summary>
        internal static string RepresentOnPos {
            get {
                return ResourceManager.GetString("RepresentOnPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservoir.
        /// </summary>
        internal static string Reservoir {
            get {
                return ResourceManager.GetString("Reservoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer receivables
        /// - residual amounts.
        /// </summary>
        internal static string residualamounts {
            get {
                return ResourceManager.GetString("residualamounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search .
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Client&apos;s Name.
        /// </summary>
        internal static string SearchClient {
            get {
                return ResourceManager.GetString("SearchClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Supplier&apos;s Name.
        /// </summary>
        internal static string SearchSupplier {
            get {
                return ResourceManager.GetString("SearchSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Color.
        /// </summary>
        internal static string SelectColor {
            get {
                return ResourceManager.GetString("SelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image .
        /// </summary>
        internal static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images Mode.
        /// </summary>
        internal static string SelectpicMode {
            get {
                return ResourceManager.GetString("SelectpicMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling.
        /// </summary>
        internal static string Selling {
            get {
                return ResourceManager.GetString("Selling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling price.
        /// </summary>
        internal static string sellingprice {
            get {
                return ResourceManager.GetString("sellingprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Price Must Be Greater than Purchase Price.
        /// </summary>
        internal static string SellPriceMore {
            get {
                return ResourceManager.GetString("SellPriceMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven.
        /// </summary>
        internal static string Seven {
            get {
                return ResourceManager.GetString("Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seventy.
        /// </summary>
        internal static string Seventy {
            get {
                return ResourceManager.GetString("Seventy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six.
        /// </summary>
        internal static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sixty.
        /// </summary>
        internal static string Sixty {
            get {
                return ResourceManager.GetString("Sixty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SR.
        /// </summary>
        internal static string SR {
            get {
                return ResourceManager.GetString("SR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Management.
        /// </summary>
        internal static string StaffManagement {
            get {
                return ResourceManager.GetString("StaffManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement.
        /// </summary>
        internal static string Statement {
            get {
                return ResourceManager.GetString("Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Added Successfuly.
        /// </summary>
        internal static string SupplierAdded {
            get {
                return ResourceManager.GetString("SupplierAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier&apos;s Data.
        /// </summary>
        internal static string SupplierData {
            get {
                return ResourceManager.GetString("SupplierData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        internal static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier&apos;s Opening Balances.
        /// </summary>
        internal static string Supplieropeningbalances {
            get {
                return ResourceManager.GetString("Supplieropeningbalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier&apos;s Receivables - Reports.
        /// </summary>
        internal static string Supplierreceivables {
            get {
                return ResourceManager.GetString("Supplierreceivables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residual amounts to suppliers.
        /// </summary>
        internal static string Supplierresidualamounts {
            get {
                return ResourceManager.GetString("Supplierresidualamounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        internal static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten.
        /// </summary>
        internal static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Method.
        /// </summary>
        internal static string TheMethod {
            get {
                return ResourceManager.GetString("TheMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thirty.
        /// </summary>
        internal static string Thirty {
            get {
                return ResourceManager.GetString("Thirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thousand.
        /// </summary>
        internal static string Thousand {
            get {
                return ResourceManager.GetString("Thousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thousands.
        /// </summary>
        internal static string Thousands {
            get {
                return ResourceManager.GetString("Thousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        internal static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrackinStore.
        /// </summary>
        internal static string TrackinStore {
            get {
                return ResourceManager.GetString("TrackinStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trillion.
        /// </summary>
        internal static string Trillion {
            get {
                return ResourceManager.GetString("Trillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trillions.
        /// </summary>
        internal static string Trillions {
            get {
                return ResourceManager.GetString("Trillions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twelve.
        /// </summary>
        internal static string Twelve {
            get {
                return ResourceManager.GetString("Twelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twenty.
        /// </summary>
        internal static string Twenty {
            get {
                return ResourceManager.GetString("Twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        internal static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Client&apos;s Data Succesfully.
        /// </summary>
        internal static string UpdatedClient {
            get {
                return ResourceManager.GetString("UpdatedClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Supplier&apos;s Data Succesfully.
        /// </summary>
        internal static string UpdatedSupplier {
            get {
                return ResourceManager.GetString("UpdatedSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email is used before .
        /// </summary>
        internal static string UsedEmail {
            get {
                return ResourceManager.GetString("UsedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Clients.
        /// </summary>
        internal static string ViewClient {
            get {
                return ResourceManager.GetString("ViewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Client Receivables.
        /// </summary>
        internal static string ViewCustomerreceivables {
            get {
                return ResourceManager.GetString("ViewCustomerreceivables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View By Expiration date.
        /// </summary>
        internal static string ViewExpirationdate {
            get {
                return ResourceManager.GetString("ViewExpirationdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Products.
        /// </summary>
        internal static string ViewProducts {
            get {
                return ResourceManager.GetString("ViewProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Suppliers.
        /// </summary>
        internal static string ViewSupplier {
            get {
                return ResourceManager.GetString("ViewSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Supplier Receivables.
        /// </summary>
        internal static string ViewSupplierreceivables {
            get {
                return ResourceManager.GetString("ViewSupplierreceivables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero.
        /// </summary>
        internal static string ZeroText {
            get {
                return ResourceManager.GetString("ZeroText", resourceCulture);
            }
        }
    }
}
